on:
  push:
    branches:
      - main

jobs:
  build: # имя взято для примера
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: make setup
      - run: make test
      - run: make lint
